apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: emailer
  name: emailer
spec:
  replicas: 1
  selector:
      matchLabels:
          name: emailer
  template:
    metadata:
      creationTimestamp: null
      labels:
              #io.kompose.service: emailer
        name: emailer
    spec:
      containers:
      - image: 10.81.1.68:5000/emailer:0.5
        name: emailer
        ports:
        - containerPort: 8009
        imagePullPolicy: IfNotPresent
        env:
        - name: EMAIL
          value: testemaildcm34@gmail.com
        - name: PASS
          value: dcmtestemail
        - name: TOMAIL
          value: testingservice9661@gmail.com
        - name: PORT
          value: "8009"
        - name: SMTP_HOST
          value: smtp.gmail.com
        - name: SMTP_SERVICE
          value: gmail
        - name: SMTP_PORT
          value: "465"
        - name: CHANGEPASSWORD_PUBLIC_IP
          value: http://10.81.1.38:30627
        - name: MS_LOGGER_IP
          value: ms-logger
        - name: MS_LOGGER_PORT
          value: "8012"
        - name: MS_LOGGER_SECRET_KEY
          value: BC2B36B81AB89F3B83AD227DCAD56
        - name: MS_LOGGER_THIS_SERVICE_NAME
          value: emailer
        - name: MS_LOGGER_THIS_SERVICE_IP
          value: emailer
        - name: MS_LOGGER_THIS_SERVICE_PORT
          value: "8009"
        - name: LOG_TARGET
          value: both
      #restartPolicy: Always
  strategy:
     type: RollingUpdate
     rollingUpdate:
       maxUnavailable: 0
       maxSurge: 1
