apiVersion: apps/v1
kind: Deployment
metadata:
  name: jboss-keycloak
  labels:
    name: jboss-keycloak
    app: jboss-keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jboss-keycloak
  template:
    metadata:
      name: jboss-keycloak
      labels:
        app: jboss-keycloak
        name: jboss-keycloak
    spec:
      restartPolicy: Always
      containers:
      - name: jboss-keycloak
        image: jboss/keycloak
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
            protocol: TCP
        env:
         - name: KEYCLOAK_LOGLEVEL
            value: "DEBUG"
          - name: KEYCLOAK_USER
            value: "admin"
          - name: KEYCLOAK_PASSWORD
            value: "admin"
          - name: JAVA_OPTS
            value: "-Dkeycloak.profile.feature.upload_scripts=enabled"
          - name: KEYCLOAK_LOGLEVEL
            value: DEBUG
          - name: KEYCLOAK_USER
            value: admin
          - name: KEYCLOAK_PASSWORD
            value: admin
          - name: DB_VENDOR
            value: MYSQL
          - name: DB_DATABASE
            value: keycloak
          - name: DB_USER
            value: keycloak
          - name: DB_PASSWORD
            value: admin
          - name: DB_ADDR
            value: "10.81.1.44"
          - name: DB_PORT
            value: "3306"

          
