apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: marketplace-be
  name: marketplace-be
spec:
  replicas: 1
  selector:
      matchLabels:
          name: marketplace-be
  template:
    metadata:
      creationTimestamp: null
      labels:
              #io.kompose.service: marketplace-be
        name: marketplace-be
    spec:
      containers:
      - image: 10.81.1.50:5000/marketplace-be:0.5
        name: marketplace-be
        ports:
        - containerPort: 9100
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_LINK
          value: mongodb://10.81.1.50:27017/ms-marketplace-be
        - name: PORT
          value: "9100"
        - name: IAM
          value: "iam:8003"
        - name: MIDDLEWARE
          value: "http://qa-middleware.ivolve.io:31907"
          
      #restartPolicy: Always
  strategy:
     type: RollingUpdate
     rollingUpdate:
       maxUnavailable: 0
       maxSurge: 1
