apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: python-app
  name: python-app
spec:
  replicas: 2
  selector:
      matchLabels:
         name: python-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: python-app
    spec:
      containers:
      - image: 10.81.1.68:5000/python-app:0.5
        name: python-app
        ports:
        - containerPort: 8002
        imagePullPolicy: IfNotPresent
        env:
        - name: OPENSTACK_HOST
          value: "192.168.1.120"
        - name: KEY_STONE_PORT
          value: "5000"
          #ms-logger serice
        - name: MS_LOGGER_THIS_SERVICE_NAME
          value: python-app
        - name: MS_LOGGER_THIS_SERVICE_IP
          value: python-app
        - name: MS_LOGGER_THIS_SERVICE_PORT
          value: "8002"
        - name: MS_LOGGER_IP
          value: ms-logger
        - name: MS_LOGGER_PORT
          value: "8012"
        - name: MS_LOGGER_SECRET_KEY
          value: BC2B36B81AB89F3B83AD227DCAD56
        - name: LOG_TARGET
          value: both
      #restartPolicy: Always
  strategy:
     type: RollingUpdate
     rollingUpdate:
        maxUnavailable: 0
        maxSurge: 1

