apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: trial-account
  name: trial-account
spec:
  replicas: 1
  selector:
      matchLabels:
          name: trial-account
  template:
    metadata:
      creationTimestamp: null
      labels:
              #io.kompose.service: trial-account
        name: trial-account
    spec:
      containers:
      - image: 10.81.1.68:5000/trial-account:1
        name: trial-account
        ports:
        - containerPort: 8020
        imagePullPolicy: IfNotPresent
        env:
        - name: NODE_ENV
          value: development
        - name: ALLOWED_ORIGIN_IP
          value: "10.81.1.89"
        - name: OPENSTACK_KEYSTONE_URL
          value: "http://10.81.1.10:5000/v3"
        - name: PORT
          value: "8020"
      #ms-logger serice
        - name: MONGODB_BASE_URL
          value: mongodb://10.81.1.89:27017/ms-trialAccount
        - name: SENDER_USERNAME
          value: "testingmailivolve@yahoo.com"
        - name: SENDER_PASSWORD
          value: password
        - name: HOST
          value: "smtp.mail.yahoo.com"
        - name: SCHEDULING_MAIL
          value: "0 */12 * * *"
        - name: ORCHESTRATOR
          value: python-app:8002
        - name: ADMINUSERNAME
          value: admin
        - name: ADMINUSERPASSWORD
          value: 8btgYd0CMEOkiylhdEqK4Qfll
        - name: ADMINUSERPROJECT
          value: 38f9940f8fcb43fba7e176b8703eb88f
          
      #restartPolicy: Always
  strategy:
     type: RollingUpdate
     rollingUpdate:
       maxUnavailable: 0
       maxSurge: 1
